# Generated by Django 3.1 on 2020-08-17 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(default='-', max_length=1000)),
                ('StudentName', models.CharField(default='-', max_length=1000)),
                ('StudentGrade', models.CharField(default='-', max_length=1000)),
                ('StudentRusalt', models.CharField(default='-', max_length=1000)),
                ('StudentTotal', models.CharField(default='-', max_length=1000)),
                ('StudentBirthday', models.DateField()),
                ('ResposveTeacher', models.CharField(default='-', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherID', models.CharField(default='-', max_length=1000)),
                ('TeacherName', models.CharField(default='-', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectID', models.CharField(default='0', max_length=1000)),
                ('SubjectName', models.CharField(default='UNKOWN', max_length=1000)),
                ('SubjectTop', models.CharField(default='100', max_length=1000)),
                ('SubjectLow', models.CharField(default='50', max_length=1000)),
                ('SubjectRusalt', models.CharField(default='-', max_length=1000)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
