# Generated by Django 3.1 on 2020-08-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='FinalExam',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='subjects',
            name='FirstExam',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='subjects',
            name='SecExam',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='subjects',
            name='ThExam',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
