# Generated by Django 3.1 on 2020-08-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200818_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='OtherMarks',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
