# Generated by Django 3.1 on 2020-08-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subjects_othermarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='StudentID',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
