# Generated by Django 3.1 on 2020-08-20 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='Msg_Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
